### ISSUE TITLE
Critical hits shouldn't ever be misses!

### ISSUE THREAD

**Issue by JohnathonNow** [a3qz/hag#123]
I landed a critical blow of 0, this doesn't make sense and shouldn't happen.
![wtf a3qz](https://user-images.githubusercontent.com/5497725/73419631-cbacc000-42ed-11ea-81ad-7bbfafafde4a.png)

**Comment by dnabre** [comment]
logic.c/player.c:player_damage_dealt() returns rng_rand(max), which may be 0. 

This is multiple by 10 - (enemy stat value), then divided by 5. So that 0 can come through so the final damage dealt may be 0. 

Criticals just double this damage value. 

So without a rule (design/game-logic wise) that says attacks and/or critical should do a minimum damage, this is not a bug.

**Comment by dnabre** [comment]
Clarification, what is the desired behavior? 

1. There's some document that covers rules/behavior that I should be finding this info in?
2. Critical should always do non-zero damage?
3. Should a critical that ends up doing zero damage be considered a miss?
4. Should a hit always do non-zero damage, which implies that critical hits will always do non-zero damage?
5. Make criticals (and maybe hits) that do zero damage gives a message indicating that you hit but failed to do damage? e.g. "You attack connects with {enemy} but fails to injure them.", "You hit the {enemy} in a vital spot but fail to penetrate its armor."
6. Do one/all/some combination of these, but tie them to fields in enemy_rulebook so the behavior can be easily configured?
7. Alternately, is the desire to make just make this not happen, pick a behavior, it can changed later if not like? 
 
I'm read through enough of the code base that doing any of would be straightforward to do. Which to do is a design/rule choice. I don't remember exactly what my previous question was. Instead of just making choice myself, I'm going by the contributing.md, and trying to discuss the change instead of just making it and throwing a

**Comment by JohnathonNow** [comment]
The intended behavior was if a critical hit were to roll for zero damage, it be considered a miss.

**Comment by JohnathonNow** [comment]
Fixed by #151.
